#ifndef GRAY_SENSOR_H
#define GRAY_SENSOR_H

#include "app_common.h"

/*
 * 8-channel red-light grayscale sensor module (AD0/AD1/AD2 + OUT multiplexed).
 *
 * All GPIO symbols (GRAY_SENSOR_PORT, GRAY_SENSOR_AD0_PIN, etc.) come from
 * ti_msp_dl_config.h, generated by gpio_software_poll.syscfg.  To change
 * pins edit the syscfg GPIO4 instance "GRAY_SENSOR" and regenerate.
 *
 * Channel order (AD2/AD1/AD0 → probe label):
 *   000 → X1    001 → X2    010 → X3    011 → X4
 *   100 → X5    101 → X6    110 → X7    111 → X8
 *
 * The default active level is 1 (black = HIGH) for red-light modules.
 * Change GRAY_ACTIVE_LEVEL to 0 if the module/track inverts this.
 */

#define GRAY_SENSOR_CHANNELS  8

#define GRAY_AD_MASK  (GRAY_SENSOR_AD0_PIN | GRAY_SENSOR_AD1_PIN | GRAY_SENSOR_AD2_PIN)

/* Active level: 1 = black-on-white (probe LOW reflectance → OUT HIGH).
   Flip to 0 if white line on dark surface. */
#ifndef GRAY_ACTIVE_LEVEL
#define GRAY_ACTIVE_LEVEL  1
#endif

/* Per-channel settle delay in microseconds (50us is sufficient for the
   CD4051-style multiplexer and comparator to stabilise). Total scan < 1 ms. */
#define GRAY_SETTLE_US  50

void gray_sensor_init(void);
void gray_sensor_read_all(uint8_t values[GRAY_SENSOR_CHANNELS]);
bool gray_sensor_has_line(const uint8_t values[GRAY_SENSOR_CHANNELS]);
bool gray_sensor_is_all_white(const uint8_t values[GRAY_SENSOR_CHANNELS]);
const char *gray_sensor_debug_string(const uint8_t values[GRAY_SENSOR_CHANNELS]);

#endif /* GRAY_SENSOR_H */
